# Generated by Django 4.2.9 on 2026-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('height', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('tall', 'Tall')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
