# Generated by Django 4.2.9 on 2026-02-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_galleryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='social/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='social/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='galleryitem',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_galleryitem_order'),
        ),
    ]
